// data.jsx — mock data for Leadgen prototype

const MOCK_TEAM = [
  { id: 'u1', name: 'Denys', role: 'Founder', initials: 'D', color: '#3D5AFE' },
  { id: 'u2', name: 'Alina', role: 'SDR', initials: 'A', color: '#F59E0B' },
  { id: 'u3', name: 'Max', role: 'Marketing Lead', initials: 'M', color: '#16A34A' },
  { id: 'u4', name: 'Kira', role: 'Copywriter', initials: 'K', color: '#EC4899' },
];

const MOCK_SESSIONS = [
  {
    id: 's-001',
    niche: 'Roofing contractors',
    region: 'New York, NY',
    status: 'done',
    createdAt: '2026-04-22T09:14:00Z',
    leadsTotal: 48,
    hot: 9, warm: 22, cold: 17,
    owner: 'u1',
    tags: ['outreach-ready', 'priority'],
  },
  {
    id: 's-002',
    niche: 'Interior designers',
    region: 'Berlin, Germany',
    status: 'done',
    createdAt: '2026-04-21T13:42:00Z',
    leadsTotal: 50,
    hot: 12, warm: 18, cold: 20,
    owner: 'u3',
    tags: ['EU', 'design'],
  },
  {
    id: 's-003',
    niche: 'Coffee shops',
    region: 'Astana, Kazakhstan',
    status: 'done',
    createdAt: '2026-04-20T17:02:00Z',
    leadsTotal: 42,
    hot: 5, warm: 14, cold: 23,
    owner: 'u2',
    tags: ['local-smb'],
  },
  {
    id: 's-004',
    niche: 'Orthodontic clinics',
    region: 'London, UK',
    status: 'running',
    createdAt: '2026-04-24T10:30:00Z',
    progress: 58,
    owner: 'u1',
    tags: ['high-ticket'],
  },
  {
    id: 's-005',
    niche: 'Yoga studios',
    region: 'Kyiv, UA',
    status: 'done',
    createdAt: '2026-04-19T08:22:00Z',
    leadsTotal: 36,
    hot: 3, warm: 12, cold: 21,
    owner: 'u4',
    tags: ['wellness'],
  },
];

const MOCK_LEADS = [
  {
    id: 'l-1', sessionId: 's-001', name: 'Northstar Roofing Co.', category: 'Roofing contractor',
    address: '1438 3rd Ave, New York, NY', phone: '+1 212 555 0184',
    website: 'northstarroofing.com', email: 'info@northstarroofing.com',
    rating: 4.7, reviews: 142, score: 92, temp: 'hot', size: 'medium',
    socials: { instagram: '@northstarroofing', facebook: 'northstarroofing' },
    tags: ['hot', 'medium', 'no-booking-widget'],
    summary: 'Established roofing firm with 15+ years in NYC. Strong review profile, weak online booking.',
    advice: 'Lead with a case study showing 30% more inbound leads after adding an instant-quote flow. They rank well organically but lose mobile visitors at the contact page — sell them a funnel audit + quote automation as a bundled pilot.',
    strengths: ['Top-tier reviews (4.7★, 142 reviews)', 'Clear service area pages', 'Active on Instagram (weekly posts)'],
    weaknesses: ['No online booking / quote form', 'Site loads in 4.8s (should be <2s)', 'No lead-magnet / retargeting pixel'],
    redFlags: [],
    status: 'new',
    owner: 'u1',
    lastTouched: '2 hours ago',
  },
  {
    id: 'l-2', sessionId: 's-001', name: 'Hudson Valley Roofers', category: 'Roofing company',
    address: '221 W 78th St, New York, NY', phone: '+1 347 555 0291',
    website: 'hudsonvalleyroofers.com', email: 'sales@hudsonvalleyroofers.com',
    rating: 4.5, reviews: 87, score: 81, temp: 'hot', size: 'small',
    socials: { instagram: '@hudson.roofers' },
    tags: ['hot', 'small', 'no-google-ads'],
    summary: 'Family-run, 2nd generation. Site is basic WordPress, no analytics pixel installed.',
    advice: 'Small team — pitch something they can run themselves after setup. A one-page lead capture + Google Local Services Ads setup would 3× their hot leads. Keep price under $3k for pilot.',
    strengths: ['Authentic local brand', 'Responsive on calls (per reviews)'],
    weaknesses: ['WordPress theme looks 2015', 'No GA/Meta pixel', 'Not running any paid ads'],
    redFlags: [],
    status: 'contacted',
    owner: 'u2',
    lastTouched: 'yesterday',
  },
  {
    id: 'l-3', sessionId: 's-001', name: 'Brooklyn Roof Works', category: 'Roofing contractor',
    address: '88 Metropolitan Ave, Brooklyn', phone: '+1 718 555 0412',
    website: 'bkroofworks.com', rating: 4.3, reviews: 64,
    score: 74, temp: 'warm', size: 'small',
    socials: {},
    tags: ['warm', 'email-only'],
    summary: 'Solid contractor, no phone listed — contact only via web form.',
    advice: 'Hardest to reach but also likely least contacted by competitors. Send a cold Loom review of their site + a specific improvement. Direct email works better than LinkedIn here.',
    strengths: ['Specialized in flat roofs (niche)', 'Portfolio photos are excellent'],
    weaknesses: ['No phone on site', 'Slow email response (per reviews)', 'No CTA above the fold'],
    redFlags: ['Missing Google Business profile phone'],
    status: 'new',
    owner: null,
    lastTouched: null,
  },
  {
    id: 'l-4', sessionId: 's-001', name: 'Apex Urban Roofing', category: 'Roofing services',
    address: '909 3rd Ave, Manhattan', phone: '+1 212 555 0770',
    website: 'apex-urban.com', rating: 4.9, reviews: 203, score: 88, temp: 'hot', size: 'large',
    socials: { instagram: '@apexurban', facebook: 'apexurban', linkedin: 'apex-urban-roofing' },
    tags: ['hot', 'large', 'has-booking'],
    summary: 'Premium commercial roofer. They already have a quote widget, but their LinkedIn is dormant.',
    advice: 'Don\'t sell a funnel — they have one. Pitch LinkedIn content production + ABM campaign targeting property managers. Higher ticket, longer cycle, but they have budget (203 reviews = volume).',
    strengths: ['Strong commercial positioning', 'Existing quote automation', 'Premium brand (clean UI)'],
    weaknesses: ['LinkedIn last post 4 months ago', 'No thought-leadership content'],
    redFlags: [],
    status: 'replied',
    owner: 'u1',
    lastTouched: '30 min ago',
  },
  {
    id: 'l-5', sessionId: 's-001', name: 'Liberty Roofing & Siding', category: 'Roofing contractor',
    address: '55 Water St, Staten Island', phone: '+1 718 555 0123',
    website: 'libertyroofsi.com', rating: 3.9, reviews: 41, score: 52, temp: 'warm', size: 'small',
    socials: { facebook: 'libertyroofsi' },
    tags: ['warm', 'low-reviews'],
    summary: 'Mixed reviews, but answers the phone fast.',
    advice: 'They need reputation management before anything else. Pitch a 90-day review campaign + targeted ads to neighborhoods where they already have 4-5★ reviews.',
    strengths: ['Fast phone response', 'Clear pricing page'],
    weaknesses: ['3.9★ average', 'Last negative review un-responded'],
    redFlags: ['1-star reviews mention no-shows'],
    status: 'new', owner: null, lastTouched: null,
  },
  {
    id: 'l-6', sessionId: 's-001', name: 'Queens Metal Roofing', category: 'Metal roofing',
    address: '14-28 Astoria Blvd, Queens', phone: '+1 718 555 0888',
    website: 'queensmetalroofing.com', rating: 4.6, reviews: 98, score: 85, temp: 'hot', size: 'medium',
    socials: { instagram: '@qmr_metal' },
    tags: ['hot', 'specialty', 'growing'],
    summary: 'Metal-roofing specialist — narrow niche, high-ticket projects.',
    advice: 'Go deep on their niche: create one cornerstone landing page "Metal Roofing NYC" with schema markup + 3 case studies. They\'ll rank #1 in 90 days. Sell SEO retainer.',
    strengths: ['Niche specialization', 'Before/after portfolio strong'],
    weaknesses: ['Generic service pages', 'No schema markup', 'Missing from local pack'],
    redFlags: [],
    status: 'contacted', owner: 'u3', lastTouched: '4 hours ago',
  },
  {
    id: 'l-7', sessionId: 's-001', name: 'Elm Ridge Roofers', category: 'Roofing',
    address: '200 Elm Ridge Rd, Yonkers', rating: 4.1, reviews: 28, score: 44, temp: 'cold', size: 'small',
    website: 'elmridgeroofers.com', phone: '+1 914 555 0331',
    socials: {}, tags: ['cold', 'no-content'],
    summary: 'Thin site, low review volume. Likely too early-stage.',
    advice: 'Skip unless they reach out. No budget indicators, no volume. Revisit in 6 months.',
    strengths: ['Located outside competitive Manhattan pack'],
    weaknesses: ['28 reviews only', 'No photo gallery', 'Owner-operator size'],
    redFlags: ['No business hours listed'],
    status: 'archived', owner: null, lastTouched: null,
  },
  {
    id: 'l-8', sessionId: 's-001', name: 'Skyline Roof Systems', category: 'Commercial roofing',
    address: '500 5th Ave, Manhattan', phone: '+1 212 555 0445',
    website: 'skylineroofsystems.com', rating: 4.8, reviews: 156, score: 90, temp: 'hot', size: 'large',
    socials: { linkedin: 'skyline-roof-systems', instagram: '@skyline.roof' },
    tags: ['hot', 'commercial', 'enterprise'],
    summary: 'Commercial-only, enterprise clients. Website is corporate but outdated CMS.',
    advice: 'This is a 6-figure account potential. Lead with case-study content marketing + LinkedIn ABM. Don\'t discount; sell retainer at premium.',
    strengths: ['Enterprise positioning', 'Strong LinkedIn presence', 'Case studies published'],
    weaknesses: ['Outdated CMS (Drupal 7)', 'Slow site performance'],
    redFlags: [],
    status: 'new', owner: 'u1', lastTouched: '15 min ago',
  },
];

// Chat assistant canned responses — maps user intent → bot flow
const ASSISTANT_GREETING = "Hi — I'm Lumen, your Leadgen copilot. Tell me who you're looking for and I'll build you a list in ~90 seconds.";

const ASSISTANT_QUICK_PROMPTS = [
  'Roofing contractors in New York',
  'Coffee shops in Astana',
  'Interior designers in Berlin',
  'Orthodontic clinics in London',
];

// Progress stages — mirrors real pipeline (google places → enrich → ai analyze → aggregate)
const PROGRESS_STAGES = [
  { key: 'parse', label: 'Parsing your request', detail: 'Understanding niche and region', duration: 1200 },
  { key: 'search', label: 'Searching Google Places', detail: 'Fetching up to 50 matching companies', duration: 2600 },
  { key: 'enrich', label: 'Enriching leads', detail: 'Websites, socials, contact details, reviews', duration: 4200 },
  { key: 'analyze', label: 'AI analysis', detail: 'Claude scoring each lead against your profile', duration: 3600 },
  { key: 'report', label: 'Building report', detail: 'Aggregating insights and packaging Excel', duration: 1200 },
];

const MOCK_USER = MOCK_TEAM[0];

Object.assign(window, {
  MOCK_USER, MOCK_TEAM, MOCK_SESSIONS, MOCK_LEADS,
  ASSISTANT_GREETING, ASSISTANT_QUICK_PROMPTS, PROGRESS_STAGES,
});
